Try again installing cli just before

diff --git a/.github/workflows/markdown_lint.yml b/.github/workflows/markdown_lint.yml
--- a/.github/workflows/markdown_lint.yml
+++ b/.github/workflows/markdown_lint.yml
@@ -22,6 +22,10 @@ jobs:
         with:
           node-version: '12'
 
+      - name: Install markdown-cli
+        id: dependencies
+        run: yarn add markdownlint-cli --dev --non-interactive --no-lockfile --prefer-offline
+
       - name: Check out code
         uses: actions/checkout@v2
 
@@ -36,48 +40,46 @@ jobs:
         run: markdownlint -i "**/template_*.md" -o "markdown-lint-report-added.txt" ${{ steps.file_changes.outputs.files_added }}
 
       # -- APPLY LINTER ------------------------------------------------------
-      - name: Install markdown-cli
-        id: dependencies
-        run: yarn add markdownlint-cli --dev --non-interactive --no-lockfile --prefer-offline
 
-      - name: Run markdownlint-cli on new files
-        id: mdl_added
-        run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-added.txt" ${{ steps.file_changes.outputs.files_added }}
 
-      - name: Run markdownlint-cli on modified files
-        id: mdl_modified
-        if: success() || failure()
-        run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-modified.txt" ${{ steps.file_changes.outputs.files_modified }}
+      # - name: Run markdownlint-cli on new files
+      #   id: mdl_added
+      #   run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-added.txt" ${{ steps.file_changes.outputs.files_added }}
 
-      # -- REPORTING ARTEFACT ------------------------------------------------
-      - name: Upload report
-        id: report_upload
-        if: success() || failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: markdown-lint-report
-          path: |
-            markdown-lint-report-added.txt
-            markdown-lint-report-modified.txt
+      # - name: Run markdownlint-cli on modified files
+      #   id: mdl_modified
+      #   if: success() || failure()
+      #   run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-modified.txt" ${{ steps.file_changes.outputs.files_modified }}
 
-      # -- USER INFORMATION --------------------------------------------------
-      - name: Comment PR - Fail
-        id: pr_comment_bad
-        if: failure()
-        uses: mshick/add-pr-comment@v1
-        with:
-          message: |
-            :boom: Erreurs repérées dans la syntaxe Markdown.
-            @${{ env.GITHUB_AUTHOR }} merci de consulter le rapport du linter (téléchargeable comme artifact). :pray:
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          allow-repeats: true
+      # # -- REPORTING ARTEFACT ------------------------------------------------
+      # - name: Upload report
+      #   id: report_upload
+      #   if: success() || failure()
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: markdown-lint-report
+      #     path: |
+      #       markdown-lint-report-added.txt
+      #       markdown-lint-report-modified.txt
 
-      - name: Comment PR - Success
-        id: pr_comment_good
-        if: success()
-        uses: mshick/add-pr-comment@v1
-        with:
-          message: |
-            :tada: Le markdown a l'air tout propre !
-          repo-token: ${{ secrets.GITHUB_TOKEN }}
-          allow-repeats: true
+      # # -- USER INFORMATION --------------------------------------------------
+      # - name: Comment PR - Fail
+      #   id: pr_comment_bad
+      #   if: failure()
+      #   uses: mshick/add-pr-comment@v1
+      #   with:
+      #     message: |
+      #       :boom: Erreurs repérées dans la syntaxe Markdown.
+      #       @${{ env.GITHUB_AUTHOR }} merci de consulter le rapport du linter (téléchargeable comme artifact). :pray:
+      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
+      #     allow-repeats: true
+
+      # - name: Comment PR - Success
+      #   id: pr_comment_good
+      #   if: success()
+      #   uses: mshick/add-pr-comment@v1
+      #   with:
+      #     message: |
+      #       :tada: Le markdown a l'air tout propre !
+      #     repo-token: ${{ secrets.GITHUB_TOKEN }}
+      #     allow-repeats: true
