Disable old linter workflow

diff --git a/.github/workflows/pr_linter_markdown.yml b/.github/workflows/pr_linter_markdown.yml
--- a/.github/workflows/pr_linter_markdown.yml
+++ b/.github/workflows/pr_linter_markdown.yml
@@ -28,55 +28,55 @@ jobs:
           reporter: github-pr-review
           markdownlint_flags: content/**/*.md
 
-  lint-markdown:
-    name: "Lint markdown files 🎳"
-    runs-on: ubuntu-latest
+  # lint-markdown:
+  #   name: "Lint markdown files 🎳"
+  #   runs-on: ubuntu-latest
 
-    steps:
-      - name: Set up NodeJS
-        uses: actions/setup-node@v2
-        with:
-          node-version: "14"
+  #   steps:
+  #     - name: Set up NodeJS
+  #       uses: actions/setup-node@v2
+  #       with:
+  #         node-version: "14"
 
-      - name: Check out code
-        uses: actions/checkout@v2
+  #     - name: Check out code
+  #       uses: actions/checkout@v2
 
-      - name: List files changes
-        id: file_changes
-        uses: trilom/file-changes-action@v1.2.4
-        with:
-          output: " "
+  #     - name: List files changes
+  #       id: file_changes
+  #       uses: trilom/file-changes-action@v1.2.4
+  #       with:
+  #         output: " "
 
-      # -- APPLY LINTER ------------------------------------------------------
-      - name: Install markdown-cli
-        id: dependencies
-        run: yarn add markdownlint-cli --dev --non-interactive --no-lockfile --prefer-offline
+  #     # -- APPLY LINTER ------------------------------------------------------
+  #     - name: Install markdown-cli
+  #       id: dependencies
+  #       run: yarn add markdownlint-cli --dev --non-interactive --no-lockfile --prefer-offline
 
-      - name: Run markdownlint-cli on new files
-        id: mdl_added
-        run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-added.txt" ${{ steps.file_changes.outputs.files_added }}
+  #     - name: Run markdownlint-cli on new files
+  #       id: mdl_added
+  #       run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-added.txt" ${{ steps.file_changes.outputs.files_added }}
 
-      - name: Run markdownlint-cli on modified files
-        id: mdl_modified
-        if: success() || failure()
-        run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-modified.txt" ${{ steps.file_changes.outputs.files_modified }}
+  #     - name: Run markdownlint-cli on modified files
+  #       id: mdl_modified
+  #       if: success() || failure()
+  #       run: yarn markdownlint -i "**/template_*.md" -o "markdown-lint-report-modified.txt" ${{ steps.file_changes.outputs.files_modified }}
 
-      # -- REPORTING ARTEFACT ------------------------------------------------
-      - name: Save environment for "child" workflow
-        if: success() || failure()
-        run: |
-          echo "PR_AUTHOR=${{ env.GITHUB_AUTHOR }}" >> pr.env
-          echo "PR_HEADSHA=${{ github.event.pull_request.head.sha }}" >> pr.env
-          echo "PR_NUMBER=${{ github.event.pull_request.number }}"    >> pr.env
-          echo "PR_TITLE=${{ github.event.pull_request.title }}"      >> pr.env
+  #     # -- REPORTING ARTEFACT ------------------------------------------------
+  #     - name: Save environment for "child" workflow
+  #       if: success() || failure()
+  #       run: |
+  #         echo "PR_AUTHOR=${{ env.GITHUB_AUTHOR }}" >> pr.env
+  #         echo "PR_HEADSHA=${{ github.event.pull_request.head.sha }}" >> pr.env
+  #         echo "PR_NUMBER=${{ github.event.pull_request.number }}"    >> pr.env
+  #         echo "PR_TITLE=${{ github.event.pull_request.title }}"      >> pr.env
 
-      - name: Upload report
-        id: report_upload
-        if: success() || failure()
-        uses: actions/upload-artifact@v2
-        with:
-          name: pr-markdown-lint-report
-          path: |
-            markdown-lint-report-added.txt
-            markdown-lint-report-modified.txt
-            pr.env
+  #     - name: Upload report
+  #       id: report_upload
+  #       if: success() || failure()
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: pr-markdown-lint-report
+  #         path: |
+  #           markdown-lint-report-added.txt
+  #           markdown-lint-report-modified.txt
+  #           pr.env
